### ISSUE TITLE
new go tools

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/shared#196]
```yml
- name: github.com/tebeka/go2xunit
  src:  https://github.com/tebeka/go2xunit
  tags: [converter]
  used:   false
  viewed: false

- name: github.com/cweill/gotests
  src:  https://github.com/cweill/gotests
  tags: [generator, tools]
  used:   false
  viewed: false

- name: github.com/golang/mock
  src:  https://github.com/golang/mock
  tags: [mock, generator, tools]
  used:   false
  viewed: false

- name: github.com/kyoh86/richgo
  src:  https://github.com/kyoh86/richgo
  tags: [cli, tools]
  used:   false
  viewed: false

- name: github.com/onsi/ginkgo
  src:  https://github.com/onsi/ginkgo
  site: http://onsi.github.io/ginkgo/
  tags: [bdd, tools]
  used:   false
  viewed: false

  useful:

  - name: github.com/onsi/gomega
    src:  https://github.com/onsi/gomega
    site: http://onsi.github.io/gomega/
    tags: []
    used:   false
    viewed: false

- name: github.com/divan/gobenchui
  src:  https://github.com/divan/gobenchui
  tags: [tools]
  used:   false
  viewed: false
```
