### ISSUE TITLE
new php tools

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/shared#197]
```yml
- name: etsy/phan
  src:  https://github.com/etsy/phan
  tags: []
  used:   false
  viewed: false

- name: jmolivas/phpqa
  src:  https://github.com/jmolivas/phpqa
  tags: []
  used:   false
  viewed: false

- name: ovr/phpsa
  src:  https://github.com/ovr/phpsa
  tags: []
  used:   false
  viewed: false

- name: pdepend/pdepend
  src:  https://github.com/pdepend/pdepend
  site: https://pdepend.org
  tags: []
  used:   false
  viewed: false

- name: phpmetrics/phpmetrics
  src:  https://github.com/phpmetrics/PhpMetrics
  site: http://www.phpmetrics.org
  tags: []
  used:   false
  viewed: false

- name: phpstan/phpstan
  src:  https://github.com/phpstan/phpstan
  tags: []
  used:   false
  viewed: false

- name: psecio/iniscan
  src:  https://github.com/psecio/iniscan
  tags: []
  used:   false
  viewed: false

- name: squizlabs/php_codesniffer
  src:  https://github.com/squizlabs/PHP_CodeSniffer
  tags: []
  used:   false
  viewed: false

  useful:

  - name: object-calisthenics/phpcs-calisthenics-rules
    src:  https://github.com/object-calisthenics/phpcs-calisthenics-rules
    tags: []
    used:   false
    viewed: false

  - name: wimg/php-compatibility
    src:  https://github.com/wimg/PHPCompatibility
    tags: []
    used:   false
    viewed: false

- name: sstalle/php7cc
  src:  https://github.com/sstalle/php7cc
  tags: []
  used:   false
  viewed: false

- name: vimeo/psalm
  src:  https://github.com/vimeo/psalm
  tags: []
  used:   false
  viewed: false

- name: povils/phpmnd
  src:  https://github.com/povils/phpmnd
  tags: []
  used:   false
  viewed: false

- name: jwage/phpchunkit
  src:  https://github.com/jwage/phpchunkit
  tags: []
  used:   false
  viewed: false
```
